module.exports =  {
    TextRegion: "TextRegion",
    ImageRegion: "ImageRegion",
    LineDrawingRegion: "LineDrawingRegion",
    GraphicRegion: "GraphicRegion",
    TableRegion: "TableRegion",
    ChartRegion: "ChartRegion",
    MapRegion: "MapRegion",
    SeparatorRegion: "SeparatorRegion",
    MathsRegion: "MathsRegion",
    ChemRegion: "ChemRegion",
    MusicRegion: "MusicRegion",
    AdvertRegion: "AdvertRegion",
    NoiseRegion: "NoiseRegion",
    UnknownRegion: "UnknownRegion",
    CustomRegion: "CustomRegion",
}