module.exports =  {
    ignore: "ignore",
    paragraph: "paragraph",
    heading: "heading",
    marginalia: "marginalia",
    page_number: "page_number",
    caption: "caption",
    header: "header",
    footer: "footer",
    drop_capital: "drop_capital",
    credit: "credit",
    floating: "floating",
    signature_mark: "signature_mark",
    catch_word: "catch_word",
    footnote: "footnote",
    footnote_continued: "footnote_continued",
    endnote: "endnote",
    TOC_entry: "TOC_entry",
    other: "other",
}